CREATE TABLE dbo.Badges(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Badges__Id PRIMARY KEY CLUSTERED,
	[Name] NVARCHAR(40) NOT NULL,
	UserId INT NOT NULL,
	[Date] DATETIME NOT NULL
);

CREATE TABLE dbo.Comments(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Comments__Id PRIMARY KEY CLUSTERED,
	CreationDate DATETIME NOT NULL,
	PostId INT NOT NULL,
	Score INT NULL,
	[Text] NVARCHAR(700) NOT NULL,
	UserId INT NULL
);

CREATE TABLE dbo.LinkTypes(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LinkTypes__Id PRIMARY KEY CLUSTERED,
	[Type] VARCHAR(50) NOT NULL
);

CREATE TABLE dbo.PostLinks(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PostLinks__Id PRIMARY KEY CLUSTERED,
	CreationDate DATETIME NOT NULL,
	PostId INT NOT NULL,
	RelatedPostId INT NOT NULL,
	LinkTypeId INT NOT NULL
);

CREATE TABLE dbo.Posts(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Posts__Id PRIMARY KEY CLUSTERED,
	AcceptedAnswerId INT NULL,
	AnswerCount INT NULL,
	Body NVARCHAR(MAX) NOT NULL,
	ClosedDate DATETIME NULL,
	CommentCount INT NULL,
	CommunityOwnedDate DATETIME NULL,
	CreationDate DATETIME NOT NULL,
	FavoriteCount INT NULL,
	LastActivityDate DATETIME NOT NULL,
	LastEditDate DATETIME NULL,
	LastEditorDisplayName NVARCHAR(40) NULL,
	LastEditorUserId INT NULL,
	OwnerUserId INT NULL,
	ParentId INT NULL,
	PostTypeId INT NOT NULL,
	Score INT NOT NULL,
	Tags NVARCHAR(150) NULL,
	Title NVARCHAR(250) NULL,
	ViewCount INT NOT NULL
);

CREATE TABLE dbo.PostTypes(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PostTypes__Id PRIMARY KEY CLUSTERED,
	[Type] NVARCHAR(50) NOT NULL
);

CREATE TABLE dbo.Users(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Users_Id PRIMARY KEY CLUSTERED,
	AboutMe NVARCHAR(MAX) NULL,
	Age INT NULL,
	CreationDate DATETIME NOT NULL,
	DisplayName NVARCHAR(40) NOT NULL,
	DownVotes INT NOT NULL,
	EmailHash NVARCHAR(40) NULL,
	LastAccessDate DATETIME NOT NULL,
	[Location] NVARCHAR(100) NULL,
	Reputation INT NOT NULL,
	UpVotes INT NOT NULL,
	Views INT NOT NULL,
	WebsiteUrl NVARCHAR(200) NULL,
	AccountId INT NULL
);

CREATE TABLE dbo.Votes(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Votes__Id PRIMARY KEY CLUSTERED,
	PostId INT NOT NULL,
	UserId INT NULL,
	BountyAmount INT NULL,
	VoteTypeId INT NOT NULL,
	CreationDate DATETIME NOT NULL
);

CREATE TABLE dbo.VoteTypes(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_VoteType__Id PRIMARY KEY CLUSTERED,
	[Name] VARCHAR(50) NOT NULL
);
